# Define configurações comuns a todos os perfis
spring:
  application:
    # Nome da aplicação (usado em logs, monitoramento, etc.)
    name: sgcc-api
  profiles:
    active: dev
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true

build:
  version: 0.0.0

# Configuração do servidor embutido
server:
  # Porta padrão da aplicação
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
