spring:
  config:
    activate:
      # Define que este bloco será ativado quando o profile "dev" estiver ativo
      on-profile: dev

  datasource:
    # URL do banco em memória H2 (uso local, rápido e descartável)
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    # Driver do banco H2
    driver-class-name: org.h2.Driver
    # Usuário padrão do H2
    username: sa
    # Senha vazia (padrão H2)
    password:

  h2:
    console:
      # Habilita console web do H2 (facilita debug do banco)
      enabled: true
      # Caminho de acesso ao console
      path: /h2-console

  jpa:
    hibernate:
      # Valida se o schema criado com flyway está correto
      ddl-auto: validate
    # Mostra queries SQL no console
    show-sql: true
    properties:
      hibernate:
        # Formata o SQL para facilitar leitura
        format_sql: true

  output:
    ansi:
      # Ativa cores no log do console
      enabled: ALWAYS

logging:
  level:
    # Nível geral do sistema
    root: INFO
    # Logs detalhados da aplicação para SUA EMPRESA
    dev.arcanus: DEBUG
    # Logs do Spring com mais detalhes
    org.springframework: INFO
    # Exibe SQL executado
    org.hibernate.SQL: INFO
    # Mostra parâmetros das queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
